version: '3'
services: 
    rollout-thrift:
        image: personali/rollout-thrift
        build: .
        ports:
            - "9090:9090"
        env_file:
            - .env
    redis:
        image: redis
