# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

#puts "thrift --gen rb -out lib/rollout-thrift/thrift ../rollout-thrift.thrift"
gemspec